version: '3.7'
services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
  mongo:
    image: mongo:3.6.21
    ports:
      - 27017:27017
    volumes:
      - ./dump:/dump
      - ./datos_db:/data/db
