version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./web/static:/var/www/static
    depends_on:
      - web
  web:
    build: .
    restart: always
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn mi_sitio_web.wsgi:application --bind 0.0.0.0:8000"
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/web
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db-data:
    driver: local
